name: Workflow 1
on:
  push:
    branches:
      - develop
      - release-prep

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build With Maven
        run: cd sistema_bancario && mvn install -DskipTests

  lint:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v3

    - name: Super-Linter
      uses: github/super-linter@v3.15.5
      env:  
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3
    - run: cd sistema_bancario && mvn clean test
